language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test_cov
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: rocky-waters-27386
  api_key: ${HEROKU_API_KEY}
